name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: | 
        cd rusty-ray/weekend
        cargo build --verbose
    - name: Linting
      run: | 
          cd rusty-ray/weekend
          cargo clippy --verbose
    - name: Run tests
      run: | 
        cd rusty-ray/weekend
        cargo test --verbose